export const NEW_ORDER_REQUST='NEW_ORDER_REQUST'
export const FAILD_NEW_ORDER='FAILD_NEW_ORDER'
export const SUCCESS_NEW_ORFDER='SUCCESS_NEW_ORFDER'
// GET ALL ORDERS OF SINGLE USER
export const GET_ORDER_REQUSET='GET_ORDER_REQUSET'
export const GET_ORDER_REQUSET_SUCCESS='GET_ORDER_REQUSET_SUCCESS'
export const GET_ORDER_REQUSET_FAIL='GET_ORDER_REQUSET_FAIL'


// TO GET single order detail
export const GET_ORDER_DETAIL_REQUSET='GET_ORDER_DETAIL_REQUSET'
export const GET_ORDER_DETAIL_REQUSET_SUCCESS='GET_ORDER_DETAIL_REQUSET_SUCCESS'
export const GET_ORDER_DETAIL_REQUSET_FAIL='GET_ORDER_DETAIL_REQUSET_FAIL'
// admin get all orders of all user
export const ADMIN_ALL_ORDER_REQ='ADMIN_ALL_ORDER_REQ'
export const ADMIN_ALL_ORDER_SUCC='ADMIN_ALL_ORDER_SUCC'
export const ADMIN_ALL_ORDER_FAIL='ADMIN_ALL_ORDER_FAIL'
// admin delete order
export const ADMIN_DELETE_ORDER_REQ= 'ADMIN_DELETE_ORDER_REQ'
export const ADMIN_DELETE_ORDER_SUCC='ADMIN_DELETE_ORDER_SUCC'
export const ADMIN_DELETE_ORDER_FAIL='ADMIN_DELETE_ORDER_FAIL'
//update order by admin
export const ADMIN_UPDATE_ORDER_REQ= 'ADMIN_UPDATE_ORDER_REQ'
export const ADMIN_UPDATE_ORDER_SUCC='ADMIN_UPDATE_ORDER_SUCC'
export const ADMIN_UPDATE_ORDER_FAIL='ADMIN_UPDATE_ORDER_FAIL'