export const USER_LOADED_FAILED="USER_LOADED_FAILED"
export const USER_LOADED_SUCCESSFULLY="USER_LOADED_SUCCESSFULLY"
export const LOAD_USER="LOAD_USER"

export const LOGIN_REQUEST_FAILED="LOGIN_REQUEST_FAILED"
export const LOGIN_REQUEST_SUCCESSFULLY="LOGIN_REQUEST_SUCCESSFULLY"
export const LOGIN_REQUEST="LOGIN_REQUEST"
// logout uder
export const LOGOUT_USER_REQUEST="LOGOUT_USER_REQUEST"
export const LOGOUT_USER_REQUEST_SUC="LOGOUT_USER_REQUEST_SUC"
export const LOGOUT_USER_REQUEST_FAIL="LOGOUT_USER_REQUEST_FAIL"
//register user
export const REGISTER_REQUEST_FAILED="REGISTER_REQUEST_FAILED"
export const REGISTER_REQUEST_SUCCESSFULLY="REGISTER_REQUEST_SUCCESSFULLY"
export const REGISTER_REQUEST="REGISTER_REQUEST"
// logout user
export const LOGOUT_REQUEST_FAILED="LOGOUT_REQUEST_FAILED"
export const LOGOUT_REQUEST_SUCCESSFULLY="LOGOUT_REQUEST_SUCCESSFULLY"
export const LOGOUT_REQUEST="LOGOUT_REQUEST"
//update profile
export const PROFILE_UPDATE_REQUEST_FAILED="PROFILE_UPDATE_REQUEST_FAILED"
export const PROFILE_UPDATE_REQUEST_SUCCESSFULLY="PROFILE_UPDATE_REQUEST_SUCCESSFULLY"
export const PROFILE_UPDATE_REQUEST="PROFILE_UPDATE_REQUEST"
// change password
export const CHANGE_PASS_REQUEST_FAILED="CHANGE_PASS_REQUEST_FAILED"
export const CHANGE_PASS_REQUEST_SUCCESSFULLY="CHANGE_PASS_REQUEST_SUCCESSFULLY"
export const CHANGE_PASS_REQUEST="CHANGE_PASS_REQUEST"
// FORGET password
export const FORGET_PASS_REQUEST_FAILED="FORGET_PASS_REQUEST_FAILED"
export const FORGET_PASS_REQUEST_SUCCESSFULLY="FORGET_PASS_REQUEST_SUCCESSFULLY"
export const FORGET_PASS_REQUEST="FORGET_PASS_REQUEST"
// reset password
export const RESET_PASS_REQUEST_FAILED="FORGET_PASS_REQUEST_FAILED"
export const RESET_PASS_REQUEST_SUCCESSFULLY="FORGET_PASS_REQUEST_SUCCESSFULLY"
export const RESET_PASS_REQUEST="FORGET_PASS_REQUEST"

// admin get all user
export const ADMIN_LOAD_ALL_USER_REQ='ADMIN_LOAD_ALL_USER_REQ'
export const ADMIN_LOAD_ALL_USER_SUCC='ADMIN_LOAD_ALL_USER_SUCC'
export const ADMIN_LOAD_ALL_USER_FAIL='ADMIN_LOAD_ALL_USER_FAIL'

// delete user by admin
export const ADMIN_DELETE_USER_REQ= 'ADMIN_DELETE_USER_REQ'
export const ADMIN_DELETE_USER_SUCC='ADMIN_DELETE_USER_SUCC'
export const ADMIN_DELETE_USER_FAIL='ADMIN_DELETE_USER_FAIL'

// load any user 
export const ADMIN_LOAD_USER_REQ= 'ADMIN_LOAD_USER_REQ'
export const ADMIN_LOAD_USER_SUCC='ADMIN_LOAD_USER_SUCC'
export const ADMIN_LOAD_USER_FAIL='ADMIN_LOAD_USER_FAIL'
// ADMIN UPDATE USER 
export const ADMIN_UPDATE_USER_REQ= 'ADMIN_UPDATE_USER_REQ'
export const ADMIN_UPDATE_USER_SUCC='ADMIN_UPDATE_USER_SUCC'
export const ADMIN_UPDATE_USER_FAIL='ADMIN_UPDATE_USER_FAIL'